name: copy packages.json from meetruck/mouse-web
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: copy packages.json
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone actionTest
        uses: actions/checkout@v2
        with:
          repository: km-blip/actionTest
          path: actionTest
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: copy packages.json.json
        run: |
            cp actionTest/package.json package.json
            npm install
            tar -zcvf libraries.tar.gz npm_modules
      - name: clean actionTest
        run: rm -rf actionTest
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'copy target.yml'
          branch: copy_target
          branch-suffix: timestamp
          delete-branch: true
          title: 'updated caches'
