name: copy packages.json from meetruck/mouse-web
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: IFtest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone actionTest
        uses: actions/checkout@v2
        with:
          repository: km-blip/actionTest
          path: actionTest
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: ifubunn
        if : hashFiles('${GITHUB_REF#refs/heads/}/package.json') != '' && (diff ./actionTest/package.json ${GITHUB_REF#refs/heads/}/package.json) == 1
        run : echo "True"
      - name: erusubunn
        if : hashFiles('${GITHUB_REF#refs/heads/}/package.json') != '' && (diff ./actionTest/package.json ${GITHUB_REF#refs/heads/}/package.json) == 0
        run : echo "False"
