name: copy packages.json from meetruck/mouse-web
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: IFtest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone actionTest
        uses: actions/checkout@v2
        with:
          repository: km-blip/actionTest
          path: actionTest
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.event.client_payload.ref }}
      - name: ifbunn2
        if : hashFiles('${GITHUB_REF#refs/heads/}/package.json') == '' && hashFiles('./actionTest/package.json') != hashFiles('${GITHUB_REF#refs/heads/}/package.json')
        run : |
            echo ${{ github.event.client_payload.sha }}
            echo ${{ github.event.client_payload.repo }}
            echo "hashFiles('${GITHUB_REF#refs/heads/}/package.json')"
            echo "make newcache"
            cat ./actionTest/hoge.txt
            mkdir -p ${GITHUB_REF#refs/heads/}/
            cp ./actionTest/package.json ${GITHUB_REF#refs/heads/}/package.json
            cd ${GITHUB_REF#refs/heads/}
            npm install
            tar -zcf libraries.tar.gz node_modules
            split -b 100m -a 2 libraries.tar.gz libraries_part.
            
      - name: erusubunn2
        if : hashFiles('${GITHUB_REF#refs/heads/}/package.json') != '' && hashFiles('./actionTest/package.json') == hashFiles('${GITHUB_REF#refs/heads/}/package.json')
        run : |
            echo "reuse cache"
            ls -la ${GITHUB_REF#refs/heads/}/
